language: node_js
node_js:
  - '8'
  - '10'
  - stable

cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - node_modules/.bin/tsc

deploy:
  provider: npm
  email: matthew.peveler@gmail.com
  api_key:
    secure: dbNYjIdzu0DtGtQLMofWFlBkU0o544NuvOB8QkVx6gR+kr1r/5G32FBlTGcZy4F47g/4ks2iIwm7ftLsdzIBaduTyRZDgWLoBRxryv6VX/tRK9pFD3MZBOuYlLD4iRdiO1T0iXKUOk177QGjvvQ44gVGqILzfz3NSLpqhIIP3R7rFIEuYAf1mFmZvwwurFVB4go+o4yoNNry7PZek+1qPNJhUK0INEdomknieTKbqaB7iEa/0IMX35ZZDk8HgUvXgx/z/dF+ilgdJxYKrjDbEi2hQz4rjFQ6RIbss7Fic0mpNDbbMDEHNjtmElr8KU4kT3UholTiyCmWRzMl/xrb3sogRZVbhi6RuxYCPTt3dCva4oswIpgGRM0v49sNnusYTZ3jYRyNUTuVaKWGTpKutmjJX50/4sIBO8KQDhlEyQv1UeTYIVRIiHl+L6oYdTDQV3c0Q8pLLeqy5/Wlr5eCWx2zPYlQZHnYYSl+c2hrjWbp1xLpAwXOcBxfACzv6BQKKnuSdE0/XtuYev7cKsWk68D+3SBLQk2CEOShaO2LzdgNmIBam0QBvUgVzoIjNpgcn9NxoWDHKr+D7GToKVmLGQLOrePKbou5S6FTfaTLl3m1Xikd2MMEMDd/k3/axosPcJ51XgW7O5OMJSC5V9cKRZ2Cb98lawVS8rwkjQQGUHk=
  on:
    tags: true
    node_js: '10'
    repo: OpenReasoning/fol-types-js
